# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: requirements_builder

on:
  push:
    paths: # only if poetry updates
      - 'pyproject.toml'
      - 'poetry.lock'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Update requirements.txt
      run: |
        poetry export --without-hashes -o requirements.txt
    - name: Push to github
      run: |
        git config user.email "github-actions@github.com"
        git config user.name "github-actions"
        git add .
        git commit -m "Update requirements.txt"
        git push
